cloudprovider: harvester

cloudCredentialSecretName: harvester

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- etcd: true
  controlplane: true
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 1

  name: harvester-nodepool-1
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/ctw-network-1
  imageName: default/image-rpj98
  vmNamespace: default
  sshUser: ubuntu
